/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginScreen.java
 *
 * Created on Oct 15, 2009, 9:32:14 AM
 */

package checkers;

import java.util.*;
/**
 *
 * @author clarkcito
 */
public class LoginScreen extends javax.swing.JFrame
{
    private static final int NEW = 0;
    private static final int ADMIN = 1;
    private static final int STATS = 2;

    private User homePlayer;
    private User visitorPlayer;
    private int boardSize;
    private String input;

    /** Creates new form LoginScreen */
    public LoginScreen()
    {
        initComponents();
    }

    public LoginScreen(int selection)
    {
        initComponents();
        
        
    }

    public LoginScreen(String homePlayer, String visitorPlayer, Date timeStamp)
    {
        initComponents();
    }

    public void getUserList ()
    {

    }

    public boolean validatePassword (String input)
    {
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(411, 296));
        getContentPane().setLayout(null);

        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(170, 143, 55, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new GameScreen(8, "h", "v").setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
