/*
 * The AboutDialog displays information about the creators and version of
 * 3D Checkers.
 */

package checkers;

public class AboutDialog extends javax.swing.JDialog {

    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconLabel = new javax.swing.JLabel();
        teamInfoLabel = new javax.swing.JLabel();
        productInfoLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setMinimumSize(new java.awt.Dimension(400, 560));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(null);

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checkers/images/3DCheckers.png"))); // NOI18N
        iconLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(iconLabel);
        iconLabel.setBounds(10, 10, 380, 323);

        teamInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        teamInfoLabel.setText("<html>3D Checkers is brought to you by the good folks at Team B.<br/>\nTeam B consists of:<br/>\nBenjamin \"Kal\" McDowd<br/>\nByron Lunt<br/>\nDavid Clark<br/>\nMike Sawtelle</html>");
        getContentPane().add(teamInfoLabel);
        teamInfoLabel.setBounds(10, 350, 380, 95);

        productInfoLabel.setBackground(new java.awt.Color(255, 255, 255));
        productInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        productInfoLabel.setText("<html><b>Product Version:</b>  3D Checkers 1.0.0");
        productInfoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        productInfoLabel.setOpaque(true);
        getContentPane().add(productInfoLabel);
        productInfoLabel.setBounds(10, 460, 380, 20);

        closeButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton);
        closeButton.setBounds(160, 500, 80, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel productInfoLabel;
    private javax.swing.JLabel teamInfoLabel;
    // End of variables declaration//GEN-END:variables

}
