/*
 * The CoinToss class uses a random generator to determine whether a coin lands
 * on heads or tails.  The player that wins the coin toss can select whether
 * they want to be the home or visitor player.
 *
 * Author:  Dave Clark
 */

package checkers;

import java.awt.Frame;
import java.util.Random;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;

public class CoinToss extends javax.swing.JDialog
{
    private final int HEADS = 0;
    private final int TAILS = 1;
    private String player1;
    private String player2;
    private String tossWinner;
    private boolean p1Home;
    private boolean randomSetup;
    private int randomNumber;
    Random random;

    //load font
    Font oldEnglish_14 = loadFont(Font.PLAIN, 14);
    Font oldEnglish_16 = loadFont(Font.PLAIN, 16);
    Font oldEnglish_17 = loadFont(Font.PLAIN, 17);
    Font oldEnglish_18 = loadFont(Font.PLAIN, 18);

    /** Creates new form CoinToss */
    public CoinToss(Frame parent, boolean modal, String p1, String p2)
    {
        super(parent, modal);
        random = new Random();

        player1 = p1;
        player2 = p2;

        initComponents();
    }

    public boolean player1Home()
    {
        return p1Home;
    }

    public boolean randomSetup()
    {
        return randomSetup;
    }

    private Font loadFont(int type, float size)
    {
        Font font = null;
        try
        {
            InputStream input = this.getClass().getResourceAsStream("/OLDENGL.TTF");
            font = Font.createFont(Font.PLAIN, input).deriveFont(type, size);
        }
        catch (IOException ioe)
        {
            System.err.println(ioe);
            System.exit(1);
        }
        catch (FontFormatException ffe)
        {
            System.err.println(ffe);
            System.exit(1);
        }
        return font;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headsTailsGroup = new javax.swing.ButtonGroup();
        homeVisitorGroup = new javax.swing.ButtonGroup();
        manualRandomGroup = new javax.swing.ButtonGroup();
        selectLabel1 = new javax.swing.JLabel();
        selectLabel2 = new javax.swing.JLabel();
        headsRadio = new javax.swing.JRadioButton();
        tailsRadio = new javax.swing.JRadioButton();
        flipButton = new javax.swing.JButton();
        homeRadio = new javax.swing.JRadioButton();
        visitorRadio = new javax.swing.JRadioButton();
        confirmButton = new javax.swing.JButton();
        infoLabel1 = new javax.swing.JLabel();
        infoLabel2 = new javax.swing.JLabel();
        setupButton = new javax.swing.JButton();
        manualRadio = new javax.swing.JRadioButton();
        randomRadio = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Coin Toss");
        setMinimumSize(new java.awt.Dimension(400, 270));
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(null);

        selectLabel1.setFont(oldEnglish_18);
        selectLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectLabel1.setText(player1 + ",");
        getContentPane().add(selectLabel1);
        selectLabel1.setBounds(30, 70, 340, 30);

        selectLabel2.setFont(oldEnglish_18);
        selectLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectLabel2.setText("please make a selection:");
        getContentPane().add(selectLabel2);
        selectLabel2.setBounds(50, 100, 300, 30);

        headsTailsGroup.add(headsRadio);
        headsRadio.setFont(oldEnglish_14);
        headsRadio.setText("Heads");
        getContentPane().add(headsRadio);
        headsRadio.setBounds(100, 140, 90, 23);

        headsTailsGroup.add(tailsRadio);
        tailsRadio.setFont(oldEnglish_14);
        tailsRadio.setText("Tails");
        getContentPane().add(tailsRadio);
        tailsRadio.setBounds(220, 140, 90, 23);

        flipButton.setFont(oldEnglish_14);
        flipButton.setText("Flip It!");
        flipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flipButtonActionPerformed(evt);
            }
        });
        getContentPane().add(flipButton);
        flipButton.setBounds(150, 180, 100, 25);

        homeVisitorGroup.add(homeRadio);
        homeRadio.setFont(oldEnglish_14);
        homeRadio.setText("Home");
        getContentPane().add(homeRadio);
        homeRadio.setBounds(100, 140, 90, 23);
        homeRadio.setVisible(false);

        homeVisitorGroup.add(visitorRadio);
        visitorRadio.setFont(oldEnglish_14);
        visitorRadio.setText("Visitor");
        getContentPane().add(visitorRadio);
        visitorRadio.setBounds(220, 140, 90, 23);
        visitorRadio.setVisible(false);

        confirmButton.setFont(oldEnglish_14);
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmButton);
        confirmButton.setBounds(150, 180, 100, 25);
        confirmButton.setVisible(false);

        infoLabel1.setFont(oldEnglish_17);
        infoLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel1.setText("A coin toss will be used to help");
        getContentPane().add(infoLabel1);
        infoLabel1.setBounds(50, 20, 300, 20);
        infoLabel1.setFont(oldEnglish_17);

        infoLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel2.setText("determine the home and visitor players.");
        getContentPane().add(infoLabel2);
        infoLabel2.setBounds(50, 40, 300, 20);
        infoLabel2.setFont(oldEnglish_17);

        setupButton.setFont(oldEnglish_14);
        setupButton.setText("Confirm");
        setupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setupButtonActionPerformed(evt);
            }
        });
        getContentPane().add(setupButton);
        setupButton.setBounds(150, 180, 100, 25);
        setupButton.setVisible(false);

        manualRandomGroup.add(manualRadio);
        manualRadio.setFont(oldEnglish_14);
        manualRadio.setText("Manual");
        getContentPane().add(manualRadio);
        manualRadio.setBounds(100, 140, 90, 23);
        manualRadio.setVisible(false);

        manualRandomGroup.add(randomRadio);
        randomRadio.setFont(oldEnglish_14);
        randomRadio.setText("Random");
        getContentPane().add(randomRadio);
        randomRadio.setBounds(220, 140, 90, 23);
        randomRadio.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void flipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flipButtonActionPerformed
        
        randomNumber = random.nextInt(2);

        //coin lands on heads and player 1 selected heads
        if (randomNumber == HEADS && headsRadio.isSelected())
        {
            tossWinner = player1;
            infoLabel2.setText("The coin landed on heads!");
        }
        //coin lands on heads and player 1 selected tails
        else if (randomNumber == HEADS && tailsRadio.isSelected())
        {
            tossWinner = player2;
            infoLabel2.setText("The coin landed on heads!");
        }
        //coin lands on tails and player 1 selected heads
        else if (randomNumber == TAILS && headsRadio.isSelected())
        {
            tossWinner = player2;
            infoLabel2.setText("The coin landed on tails!");
        }
        //coin lands on tails and player 1 selected tails
        else if (randomNumber == TAILS && tailsRadio.isSelected())
        {
            tossWinner = player1;
            infoLabel2.setText("The coin landed on tails!");
        }
        infoLabel1.setText("");

        //if the user didn't make a selection display an error
        if (!headsRadio.isSelected() && !tailsRadio.isSelected())
        {
            javax.swing.UIManager.put("OptionPane.messageFont", oldEnglish_16);
            JOptionPane.showMessageDialog(this, "Please make a selection", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        //prompt user for selection
        else
        {
            selectLabel1.setText(tossWinner + " won the toss.");
            selectLabel2.setText("Please make a selection:");

            flipButton.setVisible(false);
            tailsRadio.setVisible(false);
            headsRadio.setVisible(false);
            confirmButton.setVisible(true);
            homeRadio.setVisible(true);
            visitorRadio.setVisible(true);
        }       
    }//GEN-LAST:event_flipButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed

        //if the user didn't make a selection display an error
        if (!homeRadio.isSelected() && !visitorRadio.isSelected())
        {
            javax.swing.UIManager.put("OptionPane.messageFont", oldEnglish_16);
            JOptionPane.showMessageDialog(this, "Please make a selection",
                  "Error", JOptionPane.ERROR_MESSAGE);
        }
        //prompt user for selection
        else
        {
            infoLabel2.setText("There are two board setup options.");
            selectLabel1.setText("");
            selectLabel2.setText("Please make a selection:");

            confirmButton.setVisible(false);
            homeRadio.setVisible(false);
            visitorRadio.setVisible(false);
            setupButton.setVisible(true);
            randomRadio.setVisible(true);
            manualRadio.setVisible(true);

            //player 1 won the toss and selects home
            if (homeRadio.isSelected() && tossWinner.equals(player1))
                p1Home = true;
            //player 1 won the toss and selects visitor
            else if (visitorRadio.isSelected() && tossWinner.equals(player1))
                p1Home = false;
            //player 2 won the toss and selects visitor
            else if (visitorRadio.isSelected() && tossWinner.equals(player2))
                p1Home = true;
            //player 2 won the toss and selects home
            else if (homeRadio.isSelected() && tossWinner.equals(player2))
                p1Home = false;
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void setupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setupButtonActionPerformed

        //if the user didn't make a selection display an error
        if (!manualRadio.isSelected() && !randomRadio.isSelected())
        {
            javax.swing.UIManager.put("OptionPane.messageFont", oldEnglish_16);
            JOptionPane.showMessageDialog(this, "Please make a selection",
                  "Error", JOptionPane.ERROR_MESSAGE);
        }
        //prompt user for selection
        else
        {
            //random board setup
            if (randomRadio.isSelected())
                randomSetup = true;
            //manual board setup
            else if (manualRadio.isSelected())
                randomSetup = false;
            
            setVisible(false);
        }

}//GEN-LAST:event_setupButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton flipButton;
    private javax.swing.JRadioButton headsRadio;
    private javax.swing.ButtonGroup headsTailsGroup;
    private javax.swing.JRadioButton homeRadio;
    private javax.swing.ButtonGroup homeVisitorGroup;
    private javax.swing.JLabel infoLabel1;
    private javax.swing.JLabel infoLabel2;
    private javax.swing.JRadioButton manualRadio;
    private javax.swing.ButtonGroup manualRandomGroup;
    private javax.swing.JRadioButton randomRadio;
    private javax.swing.JLabel selectLabel1;
    private javax.swing.JLabel selectLabel2;
    private javax.swing.JButton setupButton;
    private javax.swing.JRadioButton tailsRadio;
    private javax.swing.JRadioButton visitorRadio;
    // End of variables declaration//GEN-END:variables

}
