package checkers;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
/**
 *
 * @author kalamath
 */
public class ForfeitDialog extends javax.swing.JDialog {
    User user;
    User otherUser;
//load the Old English font with a given size and type
    private Font loadFont(int type, float size)
    {
        Font font = null;
        try
        {
            InputStream input = this.getClass().getResourceAsStream("/OLDENGL.TTF");
            font = Font.createFont(Font.PLAIN, input).deriveFont(type, size);
        }
        catch (IOException ioe)
        {
            System.err.println(ioe);
            System.exit(1);
        }
        catch (FontFormatException ffe)
        {
            System.err.println(ffe);
            System.exit(1);
        }
        return font;
    }
    // load Fonts
    Font oldEnglish_18 = loadFont(Font.PLAIN, 18);
    /** Creates new form ForfeitDialog */
    public ForfeitDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public void setLabelText(String text) {
        jLabel3.setText(text);
    }
    public void setLabelIcon(boolean visitorTurn) {
        if (visitorTurn) {
            ImageIcon checkerBlack = new ImageIcon(getClass().getResource("/checkers/images/CheckerBlack.png"));
            jLabel3.setIcon(checkerBlack);
        } else {
            ImageIcon checkerRed = new ImageIcon(getClass().getResource("/checkers/images/CheckerRed.png"));
            jLabel3.setIcon(checkerRed);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("3D Checkers - Forfeit");
        setMinimumSize(new java.awt.Dimension(450, 330));
        getContentPane().setLayout(null);

        jLabel1.setFont(oldEnglish_18);
        jLabel1.setText("Are you sure you want to forfeit?");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 440, 50);

        jLabel2.setFont(oldEnglish_18);
        jLabel2.setText("Enter your password below to accept defeat.");
        jPanel2.add(jLabel2);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 50, 440, 50);

        jPanel3.setPreferredSize(new java.awt.Dimension(420, 100));
        jPanel3.setLayout(new java.awt.GridLayout());

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(120, 150, 300, 100);

        jPanel4.setLayout(null);

        jLabel3.setFont(oldEnglish_18);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel3);
        jLabel3.setBounds(0, 0, 220, 50);

        jPasswordField1.setText(null);
        jPasswordField1.setPreferredSize(new java.awt.Dimension(125, 30));
        jPanel4.add(jPasswordField1);
        jPasswordField1.setBounds(272, 10, 125, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 100, 440, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String passwordEntry = jPasswordField1.getText();
        boolean passwordMatch = passwordEntry.equalsIgnoreCase(user.getPassword());
        if (! passwordMatch) {
            JOptionPane.showMessageDialog(this, "The passwords do not match",
                    "Error", JOptionPane.WARNING_MESSAGE);
        }
        // record win for the player forfeiting, and loss for his opponent
        user.getStats().addLoss();
        otherUser.getStats().addWin();
        // update PvP stats for player forfeiting
        if (user.getStats().pvpRecords.containsKey(otherUser)) {
            user.getStats().pvpRecords.get(otherUser).addLoss();
        } else {
            user.getStats().pvpRecords.put(otherUser, new Record(0,1,0));
        }
        // update PvP stats for opponent
        if (otherUser.getStats().pvpRecords.containsKey(user)) {
            otherUser.getStats().pvpRecords.get(user).addWin();
        } else {
            otherUser.getStats().pvpRecords.put(user, new Record(1,0,0));
        }
        Main.storage.saveStorage();
        this.getOwner().dispose();
        Main.restart();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ForfeitDialog dialog = new ForfeitDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables

}
