//----------------------------------------------------------------------------
//FileName: LoadGameLogin.java
//Project: 3D Checkers
//Author: Byron Lunt
//Description: This screen is used to login the players after loading a game.
//----------------------------------------------------------------------------

package checkers;

import java.awt.Font;
import java.io.*;
import javax.swing.*;

public class LoadGameLogin extends javax.swing.JFrame {
    private Game game;
    private User VisitorPlayer;
    private User HomePlayer;
    private boolean loggedIn;


  //load the Old English font with a given size and type
    private Font loadFont(int type, float size)
    {
        Font font = null;
        try
        {
            InputStream input =
                            this.getClass().getResourceAsStream("/OLDENGL.TTF");
            font = Font.createFont(Font.PLAIN, input).deriveFont(type, size);
        }
        catch (Exception e)
        {
            System.err.println(e);
            System.exit(1);
        }
        return font;
    }
    //load fonts
    Font oldEnglish_12 = loadFont(Font.PLAIN, 12);
    Font oldEnglish_14 = loadFont(Font.PLAIN, 14);
    Font oldEnglish_16 = loadFont(Font.PLAIN, 16);
    Font oldEnglish_18 = loadFont(Font.PLAIN, 18);
    Font oldEnglish_26b = loadFont(Font.BOLD, 26);
    Font oldEnglish_36b = loadFont(Font.BOLD, 36);
    Font oldEnglish_48b = loadFont(Font.BOLD, 614);
    public LoadGameLogin()
    {
        initComponents();
    }
    //This is the constructor we will use
    public LoadGameLogin(Game game, String homePlayer, String visitorPlayer)
    {
        initComponents();
        this.game = game;
        VisitorLabel.setText(visitorPlayer);
        HomeLabel.setText(homePlayer);
        HPasswordField.setVisible(false);
        hPassword.setVisible(false);
        VPasswordField.setText(null);
        HPasswordField.setText(null);
        homeOK.setVisible(false);
        HomeLabel.setVisible(false);
        visitorPlayerNameDisplay.setVisible(true);
        homePlayerNameDisplay.setVisible(false);

        //get the User objects for use in the login screen
        for(int i = 0; i < Main.storage.getUsers().size(); i++)
        {
            if(homePlayer.equals(Main.storage.getUsers().get(i).getUserName()))
                HomePlayer = Main.storage.getUsers().get(i);
        }

        for(int i = 0; i < Main.storage.getUsers().size(); i++)
        {
            if(visitorPlayer.equals(Main.storage.getUsers().get(i).getUserName()))
                VisitorPlayer = Main.storage.getUsers().get(i);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VisitorLabel = new javax.swing.JLabel();
        HomeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TitleLabel = new javax.swing.JLabel();
        VSLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        HPasswordField = new javax.swing.JPasswordField();
        VPasswordField = new javax.swing.JPasswordField();
        visitorOK = new javax.swing.JButton();
        homeOK = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        visitorPlayerNameDisplay = new javax.swing.JLabel();
        homePlayerNameDisplay = new javax.swing.JLabel();
        hPassword = new javax.swing.JLabel();
        vPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("3D Checkers - Log In");
        setMinimumSize(new java.awt.Dimension(660, 445));
        getContentPane().setLayout(null);

        VisitorLabel.setFont(oldEnglish_26b);
        VisitorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VisitorLabel.setText("VisitorLabel");
        VisitorLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(VisitorLabel);
        VisitorLabel.setBounds(0, 130, 250, 50);

        HomeLabel.setFont(oldEnglish_26b);
        HomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLabel.setText("HomeLabel");
        HomeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HomeLabel.setMaximumSize(new java.awt.Dimension(54, 14));
        HomeLabel.setMinimumSize(new java.awt.Dimension(54, 14));
        HomeLabel.setPreferredSize(new java.awt.Dimension(54, 14));
        getContentPane().add(HomeLabel);
        HomeLabel.setBounds(400, 130, 250, 50);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 0, 0, 2);

        TitleLabel.setFont(oldEnglish_36b);
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Load Game - Log In");
        TitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(TitleLabel);
        TitleLabel.setBounds(110, 20, 436, 70);

        VSLabel.setFont(oldEnglish_26b);
        VSLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VSLabel.setText("VS");
        VSLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(VSLabel);
        VSLabel.setBounds(300, 130, 50, 50);

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checkers/images/Back_Button.png"))); // NOI18N
        BackButton.setBorder(null);
        BackButton.setBorderPainted(false);
        BackButton.setContentAreaFilled(false);
        BackButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(10, 10, 55, 55);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(-30, 80, 690, 10);

        HPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(HPasswordField);
        HPasswordField.setBounds(440, 230, 120, 20);

        VPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(VPasswordField);
        VPasswordField.setBounds(60, 230, 120, 20);

        visitorOK.setFont(new java.awt.Font("Tahoma", 0, 10));
        visitorOK.setText("OK");
        visitorOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitorOKActionPerformed(evt);
            }
        });
        getContentPane().add(visitorOK);
        visitorOK.setBounds(180, 230, 50, 21);

        homeOK.setFont(new java.awt.Font("Tahoma", 0, 10));
        homeOK.setText("OK");
        homeOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeOKActionPerformed(evt);
            }
        });
        getContentPane().add(homeOK);
        homeOK.setBounds(560, 230, 50, 21);

        visitorPlayerNameDisplay.setFont(oldEnglish_18);
        visitorPlayerNameDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checkers/images/PieceKingBlack.png"))); // NOI18N
        visitorPlayerNameDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        visitorPlayerNameDisplay.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                visitorPlayerNameDisplayComponentShown(evt);
            }
        });

        homePlayerNameDisplay.setFont(oldEnglish_18);
        homePlayerNameDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        homePlayerNameDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checkers/images/PieceKingRed.png"))); // NOI18N
        homePlayerNameDisplay.setAlignmentX(1.0F);
        homePlayerNameDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        homePlayerNameDisplay.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                homePlayerNameDisplayComponentShown(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(visitorPlayerNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195)
                .addComponent(homePlayerNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(visitorPlayerNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homePlayerNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        visitorPlayerNameDisplay.setVisible(false);
        homePlayerNameDisplay.setVisible(false);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(30, 310, 600, 100);

        hPassword.setFont(oldEnglish_14);
        hPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hPassword.setText("Password:");
        getContentPane().add(hPassword);
        hPassword.setBounds(445, 205, 100, 20);

        vPassword.setFont(oldEnglish_14);
        vPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vPassword.setText("Password:");
        getContentPane().add(vPassword);
        vPassword.setBounds(65, 205, 100, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visitorPlayerNameDisplayComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_visitorPlayerNameDisplayComponentShown
        visitorPlayerNameDisplay.setHorizontalTextPosition(SwingConstants.RIGHT);
}//GEN-LAST:event_visitorPlayerNameDisplayComponentShown

    private void homePlayerNameDisplayComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_homePlayerNameDisplayComponentShown
        homePlayerNameDisplay.setHorizontalTextPosition(SwingConstants.LEFT);
}//GEN-LAST:event_homePlayerNameDisplayComponentShown

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        //if back button is pressed return user to the load screen
        new LoadScreen().setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void visitorOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitorOKActionPerformed
       //get the password the user entered, if incorrect, display error message
       //if correct, enable the home players password field and disable the 
       // visitor player's controls.
        String passwordEntry = VPasswordField.getText();
       loggedIn = false;
       while(!loggedIn)
       {
            if (!(passwordEntry == null)) {
                if (!passwordEntry.equals(VisitorPlayer.getPassword())) {
                    JOptionPane.showMessageDialog(this, "Incorrect Password!", "Password Incorrect", JOptionPane.WARNING_MESSAGE);
                    VPasswordField.setText(null);
                    return;
                }
                loggedIn = true;
            }
       }
        //If password is correct, disabled visitor password field and enable
        //home password field
        VisitorLabel.setEnabled(false);
        VPasswordField.setEnabled(false);
        visitorOK.setEnabled(false);
        visitorPlayerNameDisplay.setVisible(false);
        hPassword.setVisible(true);
        HomeLabel.setEnabled(true);
        HPasswordField.setEnabled(true);
        homeOK.setEnabled(true);
        HomeLabel.setVisible(true);
        HPasswordField.setVisible(true);
        homeOK.setVisible(true);
        homePlayerNameDisplay.setVisible(true);
        
 
    }//GEN-LAST:event_visitorOKActionPerformed

    private void homeOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeOKActionPerformed
       //same as visitor, except if password is correct, send game file to 
       //the gamescreen constructor and resume gameplay.
        String passwordEntry = HPasswordField.getText();
       loggedIn = false;
       while(!loggedIn)
       {
            if (!(passwordEntry == null))
            {
                if (!passwordEntry.equals(HomePlayer.getPassword()))
                {
                    JOptionPane.showMessageDialog(this, "Incorrect Password!", "Password Incorrect", JOptionPane.WARNING_MESSAGE);
                    HPasswordField.setText(null);
                    return;
                }
                loggedIn = true;
            }
       }
        new GameScreen(game).setVisible(true);
        dispose();

    }//GEN-LAST:event_homeOKActionPerformed

    private void VPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VPasswordFieldActionPerformed
        
    }//GEN-LAST:event_VPasswordFieldActionPerformed

    private void HPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HPasswordFieldActionPerformed
       
    }//GEN-LAST:event_HPasswordFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPasswordField HPasswordField;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JPasswordField VPasswordField;
    private javax.swing.JLabel VSLabel;
    private javax.swing.JLabel VisitorLabel;
    private javax.swing.JLabel hPassword;
    private javax.swing.JButton homeOK;
    private javax.swing.JLabel homePlayerNameDisplay;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel vPassword;
    private javax.swing.JButton visitorOK;
    private javax.swing.JLabel visitorPlayerNameDisplay;
    // End of variables declaration//GEN-END:variables

}
