/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginScreen.java
 *
 * Created on Oct 15, 2009, 9:32:14 AM
 */

package checkers;

import java.util.*;
import javax.swing.*;
import java.io.*;
import java.awt.Font;

/**
 *
 * @author kalamath
 */
// the LoginScreen class is a GUI class, used to allow Users to log in to play
// a new game, load a saved game, or view statistics.
// the new game and load game versions require 2 players to log in, while the
// statistics version requires only a single player to log in.
public class LoginScreen extends javax.swing.JFrame
{
    private User homePlayer;
    private User visitorPlayer;
    private boolean player1LoggedIn = false;
    private boolean player2LoggedIn = false;

    //load the Old English font with a given size and type
    private Font loadFont(int type, float size)
    {
        Font font = null;
        try
        {
            InputStream oldEnglish =
                            this.getClass().getResourceAsStream("/OLDENGL.TTF");
            font = Font.createFont(Font.PLAIN, oldEnglish).deriveFont(type, size);
        }
        catch (Exception e)
        {
            System.err.println(e);
            System.exit(1);
        }
        return font;
    }
    //load fonts
    Font oldEnglish_12 = loadFont(Font.PLAIN, 12);
    Font oldEnglish_14 = loadFont(Font.PLAIN, 14);
    Font oldEnglish_16 = loadFont(Font.PLAIN, 16);
    Font oldEnglish_18 = loadFont(Font.PLAIN, 18);
    Font oldEnglish_36b = loadFont(Font.BOLD, 36);
    Font oldEnglish_48b = loadFont(Font.BOLD, 64);

    /** Creates new form LoginScreen */
    public LoginScreen()
    {
        initComponents();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        player1Button = new javax.swing.JButton();
        player1NameSelect = new javax.swing.JComboBox(Main.storage.getUsers());
        jPasswordField1 = new javax.swing.JPasswordField();
        player1OKbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        player2Button = new javax.swing.JButton();
        player2NameSelect = new javax.swing.JComboBox(Main.storage.getUsers());
        jPasswordField2 = new javax.swing.JPasswordField();
        player2OKbutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        visitorPlayerNameDisplay = new javax.swing.JLabel();
        playGameButton = new javax.swing.JButton();
        homePlayerNameDisplay = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        vsLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("3D Checkers");
        setMinimumSize(new java.awt.Dimension(660, 445));
        setName("frame78"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(oldEnglish_36b);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("New Game - Log In");
        jLabel1.setIconTextGap(1);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 20, 432, 62);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 72, 650, 10);

        jPanel1.setMinimumSize(new java.awt.Dimension(265, 135));

        player1Button.setFont(oldEnglish_18);
        player1Button.setText("Player 1 Login");
        player1Button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        player1Button.setMaximumSize(new java.awt.Dimension(170, 125));
        player1Button.setMinimumSize(new java.awt.Dimension(170, 125));
        player1Button.setPreferredSize(new java.awt.Dimension(170, 125));
        player1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(player1Button);

        player1NameSelect.setFont(oldEnglish_14);
        player1NameSelect.setMaximumSize(new java.awt.Dimension(170, 30));
        player1NameSelect.setMinimumSize(new java.awt.Dimension(170, 30));
        player1NameSelect.setPreferredSize(new java.awt.Dimension(170, 30));
        player1NameSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1NameSelectActionPerformed(evt);
            }
        });
        jPanel1.add(player1NameSelect);
        player1NameSelect.setVisible(false);

        jPasswordField1.setPreferredSize(new java.awt.Dimension(116, 20));
        jPanel1.add(jPasswordField1);
        jPasswordField1.setVisible(false);

        player1OKbutton.setText("OK");
        player1OKbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1OKbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(player1OKbutton);
        player1OKbutton.setVisible(false);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 90, 200, 200);

        player2Button.setFont(oldEnglish_18);
        player2Button.setText("Player 2 Login");
        player2Button.setEnabled(false);
        player2Button.setMaximumSize(new java.awt.Dimension(125, 125));
        player2Button.setMinimumSize(new java.awt.Dimension(125, 125));
        player2Button.setPreferredSize(new java.awt.Dimension(170, 125));
        player2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2ButtonActionPerformed(evt);
            }
        });
        jPanel2.add(player2Button);
        player2Button.setVisible(true);

        player2NameSelect.setFont(oldEnglish_14);
        player2NameSelect.setMinimumSize(new java.awt.Dimension(125, 30));
        player2NameSelect.setPreferredSize(new java.awt.Dimension(170, 30));
        player2NameSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2NameSelectActionPerformed(evt);
            }
        });
        jPanel2.add(player2NameSelect);
        player2NameSelect.setVisible(false);

        jPasswordField2.setPreferredSize(new java.awt.Dimension(116, 20));
        jPanel2.add(jPasswordField2);
        jPasswordField2.setVisible(false);

        player2OKbutton.setText("OK");
        player2OKbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2OKbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(player2OKbutton);
        player2OKbutton.setVisible(false);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(425, 90, 200, 200);

        visitorPlayerNameDisplay.setFont(oldEnglish_18);
        visitorPlayerNameDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checkers/images/PieceKingBlack.png"))); // NOI18N
        visitorPlayerNameDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        visitorPlayerNameDisplay.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                visitorPlayerNameDisplayComponentShown(evt);
            }
        });

        playGameButton.setBackground(java.awt.Color.green);
        playGameButton.setFont(oldEnglish_18);
        playGameButton.setText("Play Game!");
        playGameButton.setAlignmentX(0.5F);
        playGameButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        playGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameButtonActionPerformed(evt);
            }
        });

        homePlayerNameDisplay.setFont(oldEnglish_18);
        homePlayerNameDisplay.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        homePlayerNameDisplay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checkers/images/PieceKingRed.png"))); // NOI18N
        homePlayerNameDisplay.setAlignmentX(1.0F);
        homePlayerNameDisplay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homePlayerNameDisplay.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                homePlayerNameDisplayComponentShown(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(visitorPlayerNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(playGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(homePlayerNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visitorPlayerNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(playGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(homePlayerNameDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        visitorPlayerNameDisplay.setVisible(false);
        playGameButton.setVisible(false);
        homePlayerNameDisplay.setVisible(false);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(30, 310, 600, 100);

        jPanel4.setMinimumSize(new java.awt.Dimension(190, 220));
        jPanel4.setPreferredSize(new java.awt.Dimension(190, 220));
        jPanel4.setLayout(new java.awt.BorderLayout());

        vsLabel.setFont(oldEnglish_48b);
        vsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vsLabel.setText("VS");
        jPanel4.add(vsLabel, java.awt.BorderLayout.CENTER);

        jButton1.setFont(oldEnglish_18);
        jButton1.setText("New User");
        jButton1.setPreferredSize(new java.awt.Dimension(80, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(233, 80, 190, 220);

        backButton.setFont(oldEnglish_12);
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/checkers/images/Back_Button.png")));
        backButton.setToolTipText("Back");
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        backButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(10, 10, 55, 55);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void player2NameSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2NameSelectActionPerformed
        jPasswordField2.setText(null);
    }//GEN-LAST:event_player2NameSelectActionPerformed

    private void player2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2ButtonActionPerformed
        player2NameSelect.setModel(new DefaultComboBoxModel(Main.storage.getUsers()));
        player2NameSelect.setVisible(true);
        jPasswordField2.setVisible(true);
        player2OKbutton.setVisible(true);
    }//GEN-LAST:event_player2ButtonActionPerformed

        private void playGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameButtonActionPerformed
            Object[] options = {"8x8 Board", "10x10 Board",};
            int boardSizeSelection = -1;
            while (boardSizeSelection == -1) {
                boardSizeSelection = JOptionPane.showOptionDialog(this,
                    "Select a board size", "Board Size", JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
            }
            int width = 0;
            if (boardSizeSelection == 0) {
                width = 8;
            } else {
                width = 10;
            }
            new GameScreen(width, visitorPlayer.toString(), homePlayer.toString()).setVisible(true);
            setVisible(false);
        }//GEN-LAST:event_playGameButtonActionPerformed

        private void player1NameSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1NameSelectActionPerformed
            jPasswordField1.setText(null);

}//GEN-LAST:event_player1NameSelectActionPerformed

        private void player1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1ButtonActionPerformed
            player1NameSelect.setModel(new DefaultComboBoxModel(Main.storage.getUsers()));
            player1NameSelect.setVisible(true);
            jPasswordField1.setVisible(true);
            player1OKbutton.setVisible(true);
}//GEN-LAST:event_player1ButtonActionPerformed

        private void visitorPlayerNameDisplayComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_visitorPlayerNameDisplayComponentShown
               visitorPlayerNameDisplay.setHorizontalTextPosition(SwingConstants.RIGHT);
        }//GEN-LAST:event_visitorPlayerNameDisplayComponentShown

        private void homePlayerNameDisplayComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_homePlayerNameDisplayComponentShown
                homePlayerNameDisplay.setHorizontalTextPosition(SwingConstants.LEFT);
        }//GEN-LAST:event_homePlayerNameDisplayComponentShown

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            NewUserForm newForm = new NewUserForm(this, true);
            newForm.setVisible(true);
            player1NameSelect.setModel(new DefaultComboBoxModel(Main.storage.getUsers()));
            player2NameSelect.setModel(new DefaultComboBoxModel(Main.storage.getUsers()));
        }//GEN-LAST:event_jButton1ActionPerformed

        private void player1OKbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1OKbuttonActionPerformed
            visitorPlayer = (User) player1NameSelect.getSelectedItem();
            String passwordEntry = jPasswordField1.getText();
            if (!(passwordEntry == null)) {
                if (!passwordEntry.equals(visitorPlayer.getPassword())) {
                    JOptionPane.showMessageDialog(this, "Incorrect Password!", "Password Incorrect", JOptionPane.WARNING_MESSAGE);
                    visitorPlayer = null;
                    return;
                }
                if (visitorPlayer.equals(homePlayer)) {
                    JOptionPane.showMessageDialog(this, homePlayer + " is already logged in!", "Solitaire Mode Not Supported", JOptionPane.WARNING_MESSAGE);
                    visitorPlayer = null;
                    return;
                }
                player1Button.setEnabled(false);
                player1NameSelect.setEnabled(false);
                jPasswordField1.setEnabled(false);
                player1OKbutton.setEnabled(false);
                player2Button.setEnabled(true);
                visitorPlayerNameDisplay.setText(visitorPlayer.toString());
                visitorPlayerNameDisplay.setVisible(true);
                player1LoggedIn = true;
                if (player1LoggedIn && player2LoggedIn) {
                    playGameButton.setVisible(true);
                }
        }//GEN-LAST:event_player1OKbuttonActionPerformed
    }
            private void player2OKbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2OKbuttonActionPerformed
                homePlayer = (User) player2NameSelect.getSelectedItem();
                String passwordEntry = jPasswordField2.getText();
                if (!(passwordEntry == null)) {
                    if (!passwordEntry.equals(homePlayer.getPassword())) {
                        JOptionPane.showMessageDialog(this, "Incorrect Password!", "Password Incorrect", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    if (homePlayer.equals(visitorPlayer)) {
                        JOptionPane.showMessageDialog(this, visitorPlayer + " is already logged in!", "Solitaire Mode Not Supported", JOptionPane.WARNING_MESSAGE);
                        homePlayer = null;
                        return;
                    }
                    player2Button.setEnabled(false);
                    player2NameSelect.setEnabled(false);
                    jPasswordField2.setEnabled(false);
                    player2OKbutton.setEnabled(false);
                    homePlayerNameDisplay.setText(homePlayer.toString());
                    homePlayerNameDisplay.setVisible(true);
                    player2LoggedIn = true;
                    if (player1LoggedIn && player2LoggedIn) {
                        playGameButton.setVisible(true);
                    }
                }
            }//GEN-LAST:event_player2OKbuttonActionPerformed

                private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
                    new WelcomeScreen().setVisible(true);
                    this.setVisible(false);
                }//GEN-LAST:event_backButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel homePlayerNameDisplay;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton playGameButton;
    private javax.swing.JButton player1Button;
    public javax.swing.JComboBox player1NameSelect;
    private javax.swing.JButton player1OKbutton;
    private javax.swing.JButton player2Button;
    public javax.swing.JComboBox player2NameSelect;
    private javax.swing.JButton player2OKbutton;
    private javax.swing.JLabel visitorPlayerNameDisplay;
    private javax.swing.JLabel vsLabel;
    // End of variables declaration//GEN-END:variables

}
